version: "2"

services:

  webapps:
    image: tianon/true
    volumes:
      - ${APP_PATH}:/var/www

  workspace:
    build:
      context: ./workspace
      args:
        - PUID=${WORKSPACE_PUID}
        - PGID=${WORKSPACE_PGID}
    volumes_from:
      - webapps
    ports:
      - "${WORKSPACE_SSH_PORT}:22"
    tty: true
    networks:
      - frontend
      - backend

  supervisor:
    build: 
      context: ./supervisor
    volumes_from: 
      - webapps
    volumes: 
      - ./supervisor/conf.d:/etc/supervisor/conf.d
    networks:
      - backend
  
  mysql:
    build:
      context: ./mysql
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - backend

  php-fpm:
    build:
      context: ./php-fpm
      args:
        - PUID=${WORKSPACE_PUID}
    volumes_from:
      - webapps
    expose:
      - "9000"
    depends_on:
      - workspace
    networks:
      - backend

  redis:
    build:
      context: ./redis
    volumes:
      - ${DATA_PATH}/redis:/data
    ports:
      - "${REDIS_PORT}:6379"
    networks:
      - backend
  
  elasticsearch:
    build:
      context: ./elasticsearch
    environment:
      - ES_JAVA_OPTS=${ES_JAVA_OPTS}
    volumes:
      - ${DATA_PATH}/elasticsearch:/usr/share/elasticsearch/data
    ports:
      - "${ELASTICSEARCH_HTTP_PORT}:9200"
      - "${ELASTICSEARCH_TRANSPORT_PORT}:9300"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend  

  nginx:
    build:
      context: ./nginx
      args:
        - PUID=${WORKSPACE_PUID}
    volumes_from:
      - webapps
    volumes:
      - ${LOG_PATH}/nginx:/var/log/nginx
      - ./nginx/sites:/etc/nginx/sites-available
    ports:
      - "${HTTP_PORT}:80"
      - "${HTTPS_PORT}:443"
    depends_on:
      - php-fpm
    networks:
      - frontend
      - backend

  pusher-server:
    build: 
      context: ./pusher-server
    volumes:
      - ./pusher-server/laravel-echo-server.json:/app/laravel-echo-server.json:ro
    ports: 
      - "${PUSHER_PORT}:6001"
    links: 
      - redis
    networks: 
      - frontend
      - backend        

networks:
  frontend:
    driver: "bridge"
  backend:
    driver: "bridge"    
